# Config file for automatic testing at travis-ci.org
sudo: required

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=1.8
  - DJANGO=1.11
  - DJANGO=2.0

matrix:
  fast_finish: true
  exclude:
    - python: 3.6
      env: DJANGO=1.8

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install tox-travis -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox

after_success:
  - codecov -e TOX_ENV
