# Config file for automatic testing at travis-ci.org
sudo: false
language: python
cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

env:
  - DJANGO='Django>=1.8,<1.9'
  - DJANGO='Django>=1.11,<2.0'
  - DJANGO='Django>=2.0,<2.1'

matrix:
  fast_finish: true
  exclude:
  # Python/Django combinations that aren't officially supported
  - python: 2.7
    env: DJANGO='Django>=2.0,<2.1'

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install $DJANGO
  - pip install -r requirements.txt -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source groups_cache runtests.py

after_success:
  - codecov
